"""Find planned pauses and custom G-code blocks in a sliced Bambu / OrcaSlicer G-code file.

This module has no Home Assistant dependencies, so it can be tested on its own
and run from the command line:

    python gcode_parser.py path/to/plate_1.gcode

Timing comes from the slicer's own progress markers. ``M73 P<percent> R<minutes>``
lines appear roughly once per slicer minute, and ``R`` is the remaining time
rounded down to whole minutes. An event's position is the last ``R`` value seen
before it, plus half a minute to undo the rounding. Checked against the times
OrcaSlicer shows in its preview, this lands within a few seconds.

Filament changes (AMS swaps, ``M620`` / ``T<n>``) are ignored on purpose.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

KIND_PAUSE = "pause"
KIND_CUSTOM_GCODE = "custom_gcode"

PAUSE_TAG = "PAUSE_PRINTING"
CUSTOM_GCODE_TAG = "CUSTOM_GCODE"

# Commands that stop the printer and wait for the user.
_PAUSE_COMMAND = re.compile(r"^(M400\s+U1|M601|M600)\b", re.IGNORECASE)
_PROGRESS = re.compile(r"^M73\s+P(\d+)\s+R(\d+)")
_LAYER = re.compile(r"^M73\s+L(\d+)")
_MESSAGE = re.compile(r"^M117\s+(.*)$", re.IGNORECASE)
_TOTAL_TIME = re.compile(r"total estimated time:\s*([^;]+)")
_TOTAL_LAYERS = re.compile(r"^;\s*total layer number:\s*(\d+)")
_GENERATED_BY = re.compile(r"^;\s*generated by\s+(.+?)(?:\s+on\s+\d{4}-\d{2}-\d{2}.*)?$")
_DURATION_PART = re.compile(r"(\d+)\s*([dhms])")

# Custom G-code has no end marker, so a block is taken to end at the first
# empty or comment line, or after this many command lines.
_MAX_CUSTOM_LINES = 5
# A pause tag's own command is expected within this many lines after the tag.
_PAUSE_TAG_LOOKAHEAD = 3

_HALF_MINUTE = 0.5


@dataclass
class TimelineEvent:
    """One planned event in the print."""

    kind: str
    layer: int
    remaining_min: float
    """Slicer-estimated minutes left in the print when the event is reached."""
    elapsed_min: float
    """Slicer-estimated minutes from print start to the event."""
    line: int
    commands: list[str] = field(default_factory=list)

    @property
    def message(self) -> str | None:
        """Text of the first ``M117`` message in the block, if there is one."""
        for command in self.commands:
            if match := _MESSAGE.match(command):
                return match.group(1).strip()
        return None

    @property
    def description(self) -> str:
        if self.kind == KIND_PAUSE:
            return "Pause"
        if self.message:
            return f"Message: {self.message}"
        if self.commands:
            return f"Custom G-code: {self.commands[0]}"
        return "Custom G-code"


@dataclass
class ParsedPrint:
    """Everything the estimator needs from one G-code file."""

    slicer: str | None = None
    total_min: float | None = None
    total_layers: int | None = None
    layer_start_remaining: dict[int, float] = field(default_factory=dict)
    """Slicer minutes left at the start of each layer (1-based)."""
    progress: list[tuple[int, int]] = field(default_factory=list)
    """``(percent, remaining minutes)`` pairs in file order, from ``M73 P R`` lines."""
    events: list[TimelineEvent] = field(default_factory=list)


def parse_duration(text: str) -> float | None:
    """Turn ``"1d 3h 48m 43s"`` (any subset of parts) into minutes."""
    parts = _DURATION_PART.findall(text)
    if not parts:
        return None
    factors = {"d": 1440.0, "h": 60.0, "m": 1.0, "s": 1 / 60}
    return sum(int(value) * factors[unit] for value, unit in parts)


def parse_gcode_file(path: str | Path) -> ParsedPrint:
    with open(path, encoding="utf-8", errors="replace") as handle:
        return parse_gcode_lines(handle)


def parse_gcode_lines(lines) -> ParsedPrint:
    """Parse an iterable of G-code lines. Reads the input once, line by line."""
    result = ParsedPrint()
    remaining: float | None = None
    layer = 0
    in_executable = True
    pause_tag_lines_left = 0
    custom_event: TimelineEvent | None = None

    def add_event(kind: str, line_no: int) -> TimelineEvent:
        total = result.total_min
        if remaining is None:
            at = total if total is not None else 0.0
        else:
            at = remaining + _HALF_MINUTE
            if total is not None:
                at = min(at, total)
        elapsed = (total - at) if total is not None else 0.0
        event = TimelineEvent(kind=kind, layer=layer, remaining_min=at, elapsed_min=elapsed, line=line_no)
        result.events.append(event)
        return event

    for line_no, raw in enumerate(lines, start=1):
        line = raw.strip()

        if line.startswith(";"):
            custom_event = None
            comment = line.lstrip(";").strip()
            if comment == "EXECUTABLE_BLOCK_START":
                in_executable = True
            elif comment == "EXECUTABLE_BLOCK_END":
                in_executable = False
            elif comment == "CONFIG_BLOCK_START":
                in_executable = False
            elif comment == "CONFIG_BLOCK_END":
                in_executable = True
            elif not in_executable:
                continue
            elif comment == PAUSE_TAG:
                add_event(KIND_PAUSE, line_no)
                pause_tag_lines_left = _PAUSE_TAG_LOOKAHEAD
            elif comment == CUSTOM_GCODE_TAG:
                custom_event = add_event(KIND_CUSTOM_GCODE, line_no)
            elif result.total_min is None and (match := _TOTAL_TIME.search(line)):
                result.total_min = parse_duration(match.group(1))
            elif result.total_layers is None and (match := _TOTAL_LAYERS.match(line)):
                result.total_layers = int(match.group(1))
            elif result.slicer is None and (match := _GENERATED_BY.match(line)):
                result.slicer = match.group(1).strip()
            continue

        if not in_executable:
            continue

        if not line:
            custom_event = None
            continue

        # Drop trailing comments such as "M400 U1 ; pause".
        command = line.split(";", 1)[0].strip()

        if match := _PROGRESS.match(command):
            percent, remaining_int = int(match.group(1)), int(match.group(2))
            remaining = float(remaining_int)
            result.progress.append((percent, remaining_int))
        elif match := _LAYER.match(command):
            layer = int(match.group(1))
            if remaining is not None:
                result.layer_start_remaining.setdefault(layer, remaining + _HALF_MINUTE)

        is_pause_command = bool(_PAUSE_COMMAND.match(command))

        if custom_event is not None:
            custom_event.commands.append(command)
            if is_pause_command:
                custom_event.kind = KIND_PAUSE
            if len(custom_event.commands) >= _MAX_CUSTOM_LINES:
                custom_event = None
            continue

        if is_pause_command:
            if pause_tag_lines_left > 0:
                # This is the command belonging to the PAUSE_PRINTING tag just seen.
                result.events[-1].commands.append(command)
                pause_tag_lines_left = 0
            else:
                add_event(KIND_PAUSE, line_no).commands.append(command)
            continue

        if pause_tag_lines_left > 0:
            pause_tag_lines_left -= 1

    return result


def _format_minutes(minutes: float) -> str:
    total_seconds = round(minutes * 60)
    hours, rest = divmod(total_seconds, 3600)
    return f"{hours}:{rest // 60:02d}:{rest % 60:02d}"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: python gcode_parser.py <file.gcode>", file=sys.stderr)
        return 2
    parsed = parse_gcode_file(argv[1])
    total = _format_minutes(parsed.total_min) if parsed.total_min is not None else "unknown"
    print(f"Slicer: {parsed.slicer or 'unknown'}")
    print(f"Estimated total: {total}, layers: {parsed.total_layers or 'unknown'}")
    if not parsed.events:
        print("No pauses or custom G-code found.")
        return 0
    for event in parsed.events:
        print(
            f"  {_format_minutes(event.elapsed_min)}  layer {event.layer:>4}  "
            f"{event.description}  (line {event.line})"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
