"""Shrink a sliced G-code file into a small test fixture.

Keeps only the lines the parser cares about: the header, progress and layer
markers, pause and custom G-code blocks, AMS swaps (to test that they are
ignored) and the config line that defines the pause command (to test that
config text is not mistaken for G-code). Object names and moves are dropped,
so the fixture does not reveal what was printed.

    python scripts/trim_gcode.py input.gcode tests/fixtures/output.gcode
"""

from __future__ import annotations

import re
import sys

KEEP = re.compile(
    r"^(; HEADER_BLOCK_(START|END)"
    r"|; (generated by|model printing time|estimated first layer|total layer number)"
    r"|; (CONFIG|EXECUTABLE)_BLOCK_(START|END)"
    r"|; machine_pause_gcode ="
    r"|; layer num/total_layer_count"
    r"|; (PAUSE_PRINTING|CUSTOM_GCODE)$"
    r"|M73 "
    r"|M400 U1|M600|M601"
    r"|M62[01] S\d+A|T\d+\b)"
)
# Lines kept after a pause or custom G-code tag, so the block boundaries survive.
AFTER_TAG = 3


def trim(src: str, dst: str) -> None:
    keep_next = 0
    with open(src, encoding="utf-8", errors="replace") as fin, open(dst, "w", encoding="utf-8", newline="\n") as fout:
        for raw in fin:
            line = raw.rstrip("\r\n")
            if KEEP.match(line):
                fout.write(line + "\n")
                if line in ("; PAUSE_PRINTING", "; CUSTOM_GCODE"):
                    keep_next = AFTER_TAG
                continue
            if keep_next:
                keep_next -= 1
                # These lines only matter as block boundaries, so their content is replaced.
                if line.startswith(";"):
                    line = ";"
                elif line.startswith("G"):
                    line = "G1 E-1.6 F1800"
                fout.write(line + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__.strip().splitlines()[-1].strip(), file=sys.stderr)
        sys.exit(2)
    trim(sys.argv[1], sys.argv[2])
